#!/bin/sh /etc/rc.common
START=50

run_shadowtunnel()
{
	##var defination
	local ipaddr
	local port
	local switch
	local udp
	local pwenable
	local passwd
	local dns_enable
	local localport
	local dns
	local mode
	local hour
	local reset
	local strategy
	local encrypt
	local hosts
	local cmd
	##var assignment
	config_get switch $1 switch
	config_get udp $1 udp
	config_get passwd $1 passwd
	config_get dns_enable $1 dns_enable
	config_get mode $1 mode
	config_get hour $1 hour
	config_get reset $1 reset
	config_get strategy $1 strategy
	config_get encrypt $1 encrypt
	hosts="-dns-hosts /tmp/st_hosts.dat"
	localport="20369"
	dns="53"
	pwenable=`echo $passwd | wc -w`
	cmd="/usr/bin/shadowtunnel/shadowtunnel "
	##pre-treatment
	ip_result=`uci get /etc/config/shadowtunnel.@login[0].ipaddr | awk '{for(i=1;i<=NF;i++) printf " -f "$i}'`
	hosts_setting
	mode_select
	case $switch in
	enable)
		main_process
		;;
	disable)
		shutdown_process
		;;
	esac
	#####
	}
hosts_setting()
{
    rm -f /tmp/st_hosts.dat
    a=`uci get /etc/config/shadowtunnel.@login[0].hosts`
    printf "$a" >> /tmp/st_hosts.dat
}
mode_select()
{
	case $mode in
        GFW)
            run_mode=GFW

            ;;

        Global)
            run_mode=start

            ;;
            
    esac
}
dns_setting()
{
	case $1 in
		enable)
			uci delete dhcp.cfg02411c.nonegcache
			uci delete dhcp.cfg02411c.filterwin2k
			uci set dhcp.@dnsmasq[0].nonwildcard='0'
            		uci set dhcp.@dnsmasq[0].port='5353'
            		/etc/init.d/dnsmasq reload
            		sleep 3
			
			;;

		disable)
			uci delete dhcp.@dnsmasq[0].nonwildcard
			uci delete dhcp.@dnsmasq[0].port
			uci set dhcp.cfg02411c.nonegcache='0'
			uci set dhcp.cfg02411c.filterwin2k='0'
			/etc/init.d/dnsmasq reload
			sleep 3
			
			;;
			
	esac
}
main_process()
{
	PATH="/usr/bin/shadowtunnel/shadowtunnel "
	pwenable=`echo $passwd | wc -w`
	dns_arg=""
	passwd_arg=""
	udp_arg=""
	console_cmd=""
	case $udp in
		normal)
			;;
		udp)
			udp_arg="-U "
			;;
	esac
	case $pwenable in
		0)
			;;
		*)
			passwd_arg=" -p "${passwd}
			;;
	esac
	case $dns_enable in
		0)
			dns_setting disable
			;;
		*)
			dns_setting enable
			dns_arg=" -dns-server 8.8.8.8:53 -ttl 600 -cache /tmp/dnscache.dat -dns :"$dns
			;;
	esac
	case $mode in
        GFW)
            run_mode=GFW
			sh /etc/shadowtunnel/ipt.sh $localport $run_mode
            ;;

        Global)
            run_mode=start
			sh /etc/shadowtunnel/ipt.sh $localport $run_mode
            ;;
    esac
	console_cmd=${PATH}${udp_arg}"-E "${ip_result}" -l :"${localport}" "${dns_arg}${passwd_arg}" -lb-method "$strategy" -lb-hashtarget ""-m "$encrypt" "$hosts" -daemon -forever -redir -nolog"
	echo "test-test"
	echo $console_cmd
	
}
shutdown_process()
{
	kill -9 $(pidof shadowtunnel)
	sleep 3
	kill -9 $(pidof shadowtunnel)
	dns_setting disable 0
	sh /etc/shadowtunnel/ipt.sh $ipaddr $localport stop
	/etc/init.d/firewall restart
	rm -f /tmp/st_hosts.dat
	echo "stoped"
}
start()
{
	config_load shadowtunnel
	config_foreach run_shadowtunnel login
}

stop()
{
	echo "shadowtunnel has stoped."
}
